import { AppRole, SubscriptionStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";

export async function publicStats() { const [schools, students] = await Promise.all([prisma.school.count(), prisma.userRole.count({ where: { role: AppRole.student } })]); return { schools, students, experiments: 0 }; }
export async function superAdminStats() { const [total_schools,total_users,total_students,total_teachers,total_admins,experiments_started,experiments_completed] = await Promise.all([prisma.school.count(),prisma.profile.count(),prisma.userRole.count({where:{role:AppRole.student}}),prisma.userRole.count({where:{role:AppRole.teacher}}),prisma.userRole.count({where:{role:AppRole.school_admin}}),prisma.experimentProgress.count(),prisma.experimentProgress.count({where:{status:"completed"}})]); const schools=await prisma.school.findMany({orderBy:{name:"asc"},include:{profiles:true}}); return {total_schools,total_users,total_students,total_teachers,total_admins,experiments_started,experiments_completed,avg_time_spent:0,quizzes_taken:0,avg_quiz_score:0,school_details:schools.map(s=>({id:s.id,name:s.name,member_count:s.profiles.length,completed_experiments:0}))}; }
export async function subscriptionStats() { const all=await prisma.schoolSubscription.findMany({include:{school:{include:{profiles:true}}},orderBy:{school:{name:"asc"}}}); const sum=(status:SubscriptionStatus)=>all.filter(x=>x.status===status).length; return {total_active:sum(SubscriptionStatus.active),total_expired:sum(SubscriptionStatus.expired),total_suspended:sum(SubscriptionStatus.suspended),total_trial:sum(SubscriptionStatus.trial),total_revenue:all.filter(x=>x.status===SubscriptionStatus.active).reduce((a,x)=>a+Number(x.pricePerStudent)*x.studentCount,0),total_paying_students:all.filter(x=>x.status===SubscriptionStatus.active).reduce((a,x)=>a+x.studentCount,0),subscriptions:all.map(x=>({id:x.id,school_id:x.schoolId,school_name:x.school.name,school_location:x.school.location,school_email:x.school.email,school_phone:x.school.phone,status:x.status,student_count:x.studentCount,price_per_student:Number(x.pricePerStudent),billing_cycle:x.billingCycle,current_period_start:x.currentPeriodStart,current_period_end:x.currentPeriodEnd,activated_at:x.activatedAt,suspended_at:x.suspendedAt,notes:x.notes,total_members:x.school.profiles.length,monthly_revenue:Number(x.pricePerStudent)*x.studentCount}))}; }
export async function updateSubscription(args:{school_id:string;status?:SubscriptionStatus;student_count?:number;notes?:string}) { await prisma.schoolSubscription.update({where:{schoolId:args.school_id},data:{status:args.status,studentCount:args.student_count,notes:args.notes,suspendedAt:args.status===SubscriptionStatus.suspended?new Date():undefined}}); return {success:true}; }
export async function schoolMembers(schoolId:string) { const all=await prisma.profile.findMany({where:{schoolId},include:{user:{include:{roles:true}}},orderBy:{fullName:"asc"}}); return all.flatMap(p=>p.user.roles.map(r=>({user_id:p.userId,full_name:p.fullName,role:r.role}))); }
export async function canInvite(schoolId:string,role:string) { const sub=await prisma.schoolSubscription.findUnique({where:{schoolId}}); const users=await prisma.profile.findMany({where:{schoolId},include:{user:{include:{roles:true}}}}); const count=(wanted:AppRole)=>users.filter(p=>p.user.roles.some(r=>r.role===wanted)).length; const teachers=count(AppRole.teacher),students=count(AppRole.student), teacherSeats=sub?.teacherSeats||0, studentSeats=sub?.studentSeats||0; return {allowed:role==="teacher"?teachers<teacherSeats:role==="student"?students<studentSeats:false,teacher_seats:teacherSeats,student_seats:studentSeats,used_teachers:teachers,used_students:students,available_teachers:Math.max(teacherSeats-teachers,0),available_students:Math.max(studentSeats-students,0)}; }
export async function analytics() { const progress=await prisma.experimentProgress.findMany(); const subjects=Object.values(progress.reduce<Record<string,{subject:string,total:number,completed:number}>>((a,p)=>{const entry=a[p.subject]||{subject:p.subject,total:0,completed:0};entry.total++;if(p.status==="completed")entry.completed++;a[p.subject]=entry;return a},{})); const roles=await Promise.all(Object.values(AppRole).map(async role=>[role,await prisma.userRole.count({where:{role}})] as const)); return {experiments_by_subject:subjects,monthly_signups:[],top_schools:[],role_distribution:Object.fromEntries(roles)}; }
export async function allUsers() { const users=await prisma.profile.findMany({include:{school:true,user:{include:{roles:true}}},orderBy:{createdAt:"desc"}}); return users.flatMap(p=>p.user.roles.map(r=>({user_id:p.userId,full_name:p.fullName,avatar_url:p.avatarUrl,school_id:p.schoolId,school_name:p.school?.name||null,role:r.role,created_at:p.createdAt}))); }
